/**
 * seed.js — Caligo Pt.2 초기 데이터 마이그레이션
 * 처음 로드 시 DB가 비어있으면 이 데이터로 시드합니다.
 */

function seedDatabase(state) {
  // ── 배급사 ──
  state.distributors = [
    { id: 'dcs1774546040116', name: '공구플랫폼' },
    { id: 'dcs1774619306510', name: '디어마이뮤즈' },
    { id: 'd2', name: '메이크스타' },
    { id: 'd3', name: '무신사' },
    { id: 'dcs1774619302089', name: '버프즈' },
    { id: 'dcs1774619310313', name: '비트로드' },
    { id: 'd8', name: '애니메이트' },
    { id: 'd5', name: '영풍문고 / MusicArt' },
    { id: 'd4', name: '올리브영' },
    { id: 'dcs1774619329527', name: '케타포' },
    { id: 'dcs1774544809341', name: '훗타운' },
    { id: 'd9', name: 'Hello82' },
    { id: 'd7', name: 'HMV Japan' },
    { id: 'd10', name: 'TME (腾讯音乐)' },
    { id: 'd6', name: 'Tower Records Japan' },
    { id: 'dcs1774543391747', name: 'VLASTSHOP' },
    { id: 'dcs1774619738077', name: 'WEVERSE' },
    { id: 'd11', name: 'Will Music Taiwan' },
    { id: 'dcs1775249000000', name: '사운드웨이브' },
    { id: 'dcs1774663794920', name: '뮤직플랜트' },
    { id: 'dcs1775049442175', name: '이즈위 (一直娱)' },
    { id: 'dcs1775566277516', name: 'Universal JP' },
    { id: 'dcs1776084976682', name: '위드뮤' },
    { id: 'dcs1776085087300', name: 'Youtube' },
  ];

  // ── 분류 (Category) ──
  const catId = 'cat_caligopt2';
  state.categories = [{
    id: catId,
    name: 'Caligo Pt.2',
    artist: 'PLAVE',
    releaseDate: '2026-04-14',
    description: 'PLAVE 4th Mini Album',
    sortOrder: 1,
    createdAt: '2026-03-24',
  }];

  // ── 앨범 종류 ──
  const COUNTRY_PRICES = {
    KR: { PHOTOBOOK: 20000, POCAALBUM: 8200, ID_PASS: 14900, INVENTORY: 17100 },
    JP: { PHOTOBOOK: 3245, POCAALBUM: 1320, ID_PASS: 2420, INVENTORY: 2750 },
    CN: { PHOTOBOOK: 156, POCAALBUM: 46, ID_PASS: 78, INVENTORY: 88 },
    US: { PHOTOBOOK: 18, POCAALBUM: 8, ID_PASS: 14, INVENTORY: 16 },
    TW: { PHOTOBOOK: 560, POCAALBUM: 230, ID_PASS: 415, INVENTORY: 470 },
  };

  state.albumTypes = [
    { id: 'alb_photobook', categoryId: catId, name: '포토북', key: 'PHOTOBOOK', sortOrder: 1, countryPrices: { KR: 20000, JP: 3245, CN: 156, US: 18, TW: 560 } },
    { id: 'alb_pocaalbum', categoryId: catId, name: '포카앨범', key: 'POCAALBUM', sortOrder: 2, countryPrices: { KR: 8200, JP: 1320, CN: 46, US: 8, TW: 230 } },
    { id: 'alb_idpass', categoryId: catId, name: '아이디패스', key: 'ID_PASS', sortOrder: 3, countryPrices: { KR: 14900, JP: 2420, CN: 78, US: 14, TW: 415 } },
    { id: 'alb_inventory', categoryId: catId, name: '인벤토리', key: 'INVENTORY', sortOrder: 4, countryPrices: { KR: 17100, JP: 2750, CN: 88, US: 16, TW: 470 } },
  ];

  // ── 판매처 (stores with categoryId, round, isMusicStreamTeam) ──
  // round: null = 단독, 1 = 1차, 2 = 2차 ...
  // isMusicStreamTeam: 음원총공팀 연계
  state.stores = [
    {
      id: 'cs1774546479074', categoryId: catId,
      name: '길보드 (ASTERUM 433-10)',
      distId: '', country: 'KR',
      round: null, isMusicStreamTeam: false,
      unpoAlbumKey: 'POCAALBUM',
      priceMode: 'country', customPrices: {},
      purchaseStart: '2026-04-20T15:00', purchaseEnd: '2026-04-20T23:00',
      offlineStart: '2026-04-20', offlineEnd: '2026-04-20',
      offlineHours: '15:00 - 23:00', offlineAddress: '서대문구 연희로11가길 48-23',
      offlineNote: '모든 버전 구매시 A2T DRAW (십카페 럭드) 와 동일한 포카 중 랜덤 1종 증정\n럭드 포토카드중 친필사인 포토카드 랜덤 제공',
      offlineLuckyDraw: true, defDomShip: 0, defOvsShip: 0,
      url: 'https://caligopt2popup.oopy.io/', defDeliveryDate: '',
      videocall: false, memo: '',
    },
    {
      id: 'cs1774546314667', categoryId: catId,
      name: '더현대서울',
      distId: '', country: 'KR',
      round: null, isMusicStreamTeam: false,
      unpoAlbumKey: 'POCAALBUM',
      priceMode: 'country', customPrices: {},
      purchaseStart: '2026-04-14T10:30', purchaseEnd: '2026-04-19T14:00',
      offlineStart: '2026-04-14', offlineEnd: '2026-04-19',
      offlineHours: '(화-목) 10:30 - 20:00 ; (금-일) 10:30 - 20:30',
      offlineAddress: '더현대서울 5F',
      offlineNote: '모든 버전 구매시 더현대럭키드로우 포토카드 5종중 랜덤 증정',
      offlineLuckyDraw: true, defDomShip: 0, defOvsShip: 0,
      url: '', defDeliveryDate: '', videocall: false, memo: '',
    },
    {
      id: 's3', categoryId: catId,
      name: '메이크스타', distId: 'd2', country: 'KR',
      round: null, isMusicStreamTeam: false,
      unpoAlbumKey: 'POCAALBUM',
      priceMode: 'country', customPrices: {},
      purchaseStart: '2026-03-24T11:00', purchaseEnd: '2026-04-20T19:59',
      offlineStart: '2026-04-14', offlineEnd: '2026-04-20',
      offlineHours: '매일 12:00~20:00', offlineAddress: '서울시 학동로23길 29 B1',
      offlineNote: '[강남] MAKESTAR SPACE GANGNAM',
      offlineLuckyDraw: false, defDomShip: 3000, defOvsShip: 0,
      url: 'https://www.makestar.com/product/16439', defDeliveryDate: '',
      videocall: false,
      memo: 'POCAALBUM ver. 구매 시 미공개 포토카드 1매 랜덤 증정\n*총 5종, 앨범 1매 당 랜덤 1매',
    },
    {
      id: 's4', categoryId: catId,
      name: '무신사 (1차)', distId: 'd3', country: 'KR',
      round: 1, isMusicStreamTeam: false,
      unpoAlbumKey: 'ID_PASS',
      priceMode: 'country', customPrices: {},
      purchaseStart: '2026-03-24T11:00', purchaseEnd: '2026-04-13T23:59',
      offlineStart: '', offlineEnd: '', offlineHours: '', offlineAddress: '', offlineNote: '',
      offlineLuckyDraw: false, defDomShip: 0, defOvsShip: 0,
      url: 'https://www.musinsa.com/search/goods?keyword=PLAVE+4th+Mini+Album+Caligo+Pt.2',
      defDeliveryDate: '', videocall: false,
      memo: '구매 수량에 맞춰 1:1 랜덤 증정\n온라인: 한 주문번호 내 앨범 2장 구매 시 중복없이 증정',
    },
    {
      id: 's5', categoryId: catId,
      name: '무신사 (2차)', distId: 'd3', country: 'KR',
      round: 2, isMusicStreamTeam: false,
      unpoAlbumKey: 'ID_PASS',
      priceMode: 'country', customPrices: {},
      purchaseStart: '2026-04-14T11:00', purchaseEnd: '2026-04-20T23:00',
      offlineStart: '2026-04-14', offlineEnd: '2026-04-20',
      offlineHours: '11:00~10:00', offlineAddress: '',
      offlineNote: '무신사 스토어 성수 / 무신사 스토어 명동',
      offlineLuckyDraw: false, defDomShip: 0, defOvsShip: 0,
      url: 'https://www.musinsa.com/search/goods?keyword=PLAVE+4th+Mini+Album+Caligo+Pt.2',
      defDeliveryDate: '', videocall: false,
      memo: 'ID PASS 구매 시 미공포 (온오프동일)',
    },
    {
      id: 's10', categoryId: catId,
      name: '애니메이트', distId: 'd8', country: 'KR',
      round: null, isMusicStreamTeam: false,
      unpoAlbumKey: 'ID_PASS',
      priceMode: 'custom',
      customPrices: { PHOTOBOOK: null, POCAALBUM: null, ID_PASS: 14900, INVENTORY: null },
      purchaseStart: '2026-03-24T11:00', purchaseEnd: '2026-04-08T23:59',
      purchaseEndTxt: '특전 소진시까지',
      offlineStart: '2026-04-14', offlineEnd: '2026-05-31',
      offlineHours: '', offlineAddress: '애니메이트 홍대점, 잠실롯데점, 부산점',
      offlineNote: '그라떼 7천원 / 아이싱쿠키 6,500원',
      offlineLuckyDraw: false, defDomShip: 0, defOvsShip: 0,
      url: 'https://animate-onlineshop.co.kr/goods/goods_view.php?goodsNo=1000089045',
      defDeliveryDate: '', videocall: false,
      memo: '특전: 포토카드 (전 5종 1세트 증정)【미공개 포토카드】',
    },
    {
      id: 's7', categoryId: catId,
      name: '영풍문고 (뮤직아트)', distId: 'd5', country: 'KR',
      round: null, isMusicStreamTeam: false,
      unpoAlbumKey: 'POCAALBUM',
      priceMode: 'country', customPrices: {},
      purchaseStart: '2026-03-24T11:00', purchaseEnd: '2026-04-20T22:00',
      offlineStart: '2026-04-14', offlineEnd: '2026-04-20',
      offlineHours: '10:00 - 22:00',
      offlineAddress: 'the stage by Musicart (청계천로 41 B2) / 영풍문고 여의도 IFC몰점 / 영풍문고 홍대점',
      offlineNote: '', offlineLuckyDraw: false, defDomShip: 3000, defOvsShip: 0,
      url: 'http://musicart.kr/shop/shopdetail.html?branduid=3530779',
      defDeliveryDate: '', videocall: false,
      memo: 'POCAALBUM 구매 시 미공포 (온오프동일)',
    },
    {
      id: 's6', categoryId: catId,
      name: '올리브영', distId: 'd4', country: 'KR',
      round: null, isMusicStreamTeam: false,
      unpoAlbumKey: 'ID_PASS',
      priceMode: 'country', customPrices: {},
      purchaseStart: '2026-03-24T11:00', purchaseEnd: '2026-04-20T22:00',
      offlineStart: '2026-04-14', offlineEnd: '2026-04-20',
      offlineHours: '', offlineAddress: '올리브영N 성수 / 올리브영 홍대놀이터점',
      offlineNote: '', offlineLuckyDraw: false, defDomShip: 0, defOvsShip: 0,
      url: 'https://www.oliveyoung.co.kr/store/planshop/getPlanShopDetail.do?dispCatNo=500000100018171',
      defDeliveryDate: '', videocall: false,
      memo: 'ID PASS 구매 시 미공포 (온오프동일)',
    },
    {
      id: 's8', categoryId: catId,
      name: '타워레코드', distId: 'd6', country: 'JP',
      round: null, isMusicStreamTeam: false,
      unpoAlbumKey: 'ID_PASS',
      priceMode: 'custom',
      customPrices: { PHOTOBOOK: 3590, POCAALBUM: 1890, ID_PASS: 2420, INVENTORY: 3490 },
      purchaseStart: '2026-03-24T11:00', purchaseEnd: '',
      purchaseEndTxt: '특전 소진시까지',
      offlineStart: '', offlineEnd: '', offlineHours: '', offlineAddress: '', offlineNote: '',
      offlineLuckyDraw: false, defDomShip: 0, defOvsShip: 1210,
      url: 'https://tower.jp/search/item/plave%20caligo%20pt%EF%BC%8E2',
      defDeliveryDate: '', videocall: false, memo: '',
    },
    {
      id: 'cs1774546219159', categoryId: catId,
      name: '[음총] 타워레코드 (1차)', distId: 'dcs1774546040116', country: 'KR',
      round: 1, isMusicStreamTeam: true,
      unpoAlbumKey: 'ID_PASS',
      priceMode: 'custom',
      customPrices: { PHOTOBOOK: null, POCAALBUM: null, ID_PASS: 24410, INVENTORY: null },
      purchaseStart: '2026-03-24T11:00', purchaseEnd: '2026-03-29T23:59',
      offlineStart: '', offlineEnd: '', offlineHours: '', offlineAddress: '', offlineNote: '',
      offlineLuckyDraw: false, defDomShip: 0, defOvsShip: 0,
      url: 'https://x.com/Plave_Album/status/2036341423856034026?s=20',
      defDeliveryDate: '2026-05-01', videocall: false,
      memo: '출고 일정 : 05월 초 ~ 05월 중 예상',
    },
    {
      id: 's11', categoryId: catId,
      name: 'Hello82 (예판)', distId: 'd9', country: 'US',
      round: null, isMusicStreamTeam: false,
      unpoAlbumKey: 'ID_PASS',
      priceMode: 'country', customPrices: {},
      purchaseStart: '2026-03-24T11:00', purchaseEnd: '2026-04-17T23:59',
      offlineStart: '', offlineEnd: '', offlineHours: '', offlineAddress: '', offlineNote: '',
      offlineLuckyDraw: false, defDomShip: 0, defOvsShip: 0,
      url: 'https://hello82.com/search?q=plave',
      defDeliveryDate: '', videocall: false, memo: '"BITE" ver',
    },
    {
      id: 's12', categoryId: catId,
      name: 'Hello82 (팝업)', distId: 'd9', country: 'US',
      round: null, isMusicStreamTeam: false,
      unpoAlbumKey: 'ID_PASS',
      priceMode: 'country', customPrices: {},
      purchaseStart: '2026-03-24T11:00', purchaseEnd: '2026-04-17T23:59',
      offlineStart: '', offlineEnd: '', offlineHours: '', offlineAddress: '', offlineNote: '',
      offlineLuckyDraw: false, defDomShip: 0, defOvsShip: 0,
      url: 'https://hello82.com/search?q=plave',
      defDeliveryDate: '', videocall: false, memo: '"LOOKUP" ver',
    },
    {
      id: 's9', categoryId: catId,
      name: 'HMV', distId: 'd7', country: 'JP',
      round: null, isMusicStreamTeam: false,
      unpoAlbumKey: 'ID_PASS',
      priceMode: 'custom',
      customPrices: { PHOTOBOOK: 4070, POCAALBUM: 1979, ID_PASS: 2420, INVENTORY: 3740 },
      purchaseStart: '2026-03-24T11:00', purchaseEnd: '',
      purchaseEndTxt: '특전 소진시까지',
      offlineStart: '', offlineEnd: '', offlineHours: '', offlineAddress: '', offlineNote: '',
      offlineLuckyDraw: false, defDomShip: 0, defOvsShip: 330,
      url: 'https://www.hmv.co.jp/en/news/article/260317125/',
      defDeliveryDate: '', videocall: false,
      memo: '인벤토리를 제외하고 세트판매하지않음',
    },
    {
      id: 'cs1774546033455', categoryId: catId,
      name: 'HMV (1차)', distId: 'dcs1774546040116', country: 'KR',
      round: 1, isMusicStreamTeam: true,
      unpoAlbumKey: 'ID_PASS',
      priceMode: 'custom',
      customPrices: { PHOTOBOOK: null, POCAALBUM: null, ID_PASS: 24412, INVENTORY: null },
      purchaseStart: '2026-03-24T02:28', purchaseEnd: '2026-03-29T23:59',
      offlineStart: '', offlineEnd: '', offlineHours: '', offlineAddress: '', offlineNote: '',
      offlineLuckyDraw: false, defDomShip: 0, defOvsShip: 0,
      url: 'https://x.com/Plave_Album/status/2036341423856034026?s=20',
      defDeliveryDate: '', videocall: false, memo: '',
    },
    {
      id: 's13', categoryId: catId,
      name: 'TME', distId: 'd10', country: 'CN',
      round: null, isMusicStreamTeam: false,
      unpoAlbumKey: 'PHOTOBOOK',
      priceMode: 'country', customPrices: {},
      purchaseStart: '2026-03-24T11:00', purchaseEnd: '2026-04-20T23:59',
      offlineStart: '', offlineEnd: '', offlineHours: '', offlineAddress: '', offlineNote: '',
      offlineLuckyDraw: false, defDomShip: 0, defOvsShip: 70,
      url: 'https://i2.y.qq.com/n3/cm/pages/putao/product_detail/index.html?productID=1205354113456059',
      defDeliveryDate: '', videocall: false,
      memo: '5종 중 랜덤 1종 / 5장 구매 시 한 세트 완성',
    },
    {
      id: 'cs1774545021788', categoryId: catId,
      name: '[음총] TME', distId: 'dcs1774544809341', country: 'KR',
      round: null, isMusicStreamTeam: true,
      unpoAlbumKey: 'PHOTOBOOK',
      priceMode: 'custom',
      customPrices: { PHOTOBOOK: 22683, POCAALBUM: null, ID_PASS: null, INVENTORY: null },
      purchaseStart: '2026-03-24T11:00', purchaseEnd: '2026-03-27T08:00',
      purchaseEndTxt: '특전 소진시까지',
      offlineStart: '', offlineEnd: '', offlineHours: '', offlineAddress: '', offlineNote: '',
      offlineLuckyDraw: false, defDomShip: 0, defOvsShip: 0,
      url: 'https://x.com/Plave_Album/status/2036611347409231996?s=20',
      defDeliveryDate: '', videocall: false,
      memo: '5종 중 랜덤 1종 / 5장 구매 시 한 세트 완성',
    },
    {
      id: 's1', categoryId: catId,
      name: 'VLAST SHOP', distId: 'dcs1774543391747', country: 'KR',
      round: null, isMusicStreamTeam: false,
      unpoAlbumKey: 'PHOTOBOOK',
      priceMode: 'country', customPrices: {},
      purchaseStart: '2026-03-24T11:00', purchaseEnd: '2026-03-27T23:59',
      offlineStart: '', offlineEnd: '', offlineHours: '', offlineAddress: '', offlineNote: '',
      offlineLuckyDraw: false, defDomShip: 0, defOvsShip: 0,
      url: 'https://vlastshop.com/product/search.html?banner_action=&keyword=PLAVE+Caligo+Pt.2',
      defDeliveryDate: '', videocall: true, memo: '',
    },
    {
      id: 's2', categoryId: catId,
      name: 'Weverse Shop', distId: 'dcs1774619738077', country: 'KR',
      round: null, isMusicStreamTeam: false,
      unpoAlbumKey: 'POCAALBUM',
      priceMode: 'country', customPrices: {},
      purchaseStart: '2026-03-24T11:00', purchaseEnd: '2026-04-13T23:59',
      offlineStart: '', offlineEnd: '', offlineHours: '', offlineAddress: '', offlineNote: '',
      offlineLuckyDraw: false, defDomShip: 3000, defOvsShip: 0,
      url: 'https://shop.weverse.io/ko/shop/KRW/artists/167/categories/3719',
      defDeliveryDate: '', videocall: false, memo: '',
    },
    {
      id: 's14', categoryId: catId,
      name: 'Will Music', distId: 'd11', country: 'TW',
      round: null, isMusicStreamTeam: false,
      unpoAlbumKey: 'POCAALBUM',
      priceMode: 'country', customPrices: {},
      purchaseStart: '2026-03-24T11:00', purchaseEnd: '2026-04-20T23:59',
      offlineStart: '', offlineEnd: '', offlineHours: '', offlineAddress: '', offlineNote: '',
      offlineLuckyDraw: false, defDomShip: 0, defOvsShip: 0,
      url: 'https://www.willmusic.com.tw/SalePage/Index/11651010',
      defDeliveryDate: '', videocall: false, memo: '',
    },
    {
      id: 'cs1774545187345', categoryId: catId,
      name: '[음총] Will Music', distId: 'dcs1774544809341', country: 'KR',
      round: null, isMusicStreamTeam: true,
      unpoAlbumKey: 'POCAALBUM',
      priceMode: 'custom',
      customPrices: { PHOTOBOOK: null, POCAALBUM: 10506, ID_PASS: null, INVENTORY: null },
      purchaseStart: '2026-03-24T11:00', purchaseEnd: '2026-04-13T23:59',
      offlineStart: '', offlineEnd: '', offlineHours: '', offlineAddress: '', offlineNote: '',
      offlineLuckyDraw: false, defDomShip: 0, defOvsShip: 0,
      url: 'https://x.com/Plave_Album/status/2036611347409231996?s=20',
      defDeliveryDate: '', videocall: false, memo: '',
    },
    {
      id: 'cs1774545937612', categoryId: catId,
      name: '[음총] 디어마이뮤즈', distId: 'dcs1774619306510', country: 'KR',
      round: null, isMusicStreamTeam: true,
      unpoAlbumKey: '',
      priceMode: 'custom',
      customPrices: { PHOTOBOOK: 16500, POCAALBUM: 6900, ID_PASS: 1200, INVENTORY: 14200 },
      purchaseStart: '2026-03-24T02:25', purchaseEnd: '2026-04-14T19:00',
      offlineStart: '', offlineEnd: '', offlineHours: '', offlineAddress: '', offlineNote: '',
      offlineLuckyDraw: false, defDomShip: 0, defOvsShip: 0,
      url: 'https://x.com/Plave_Album/status/2036340525821993312?s=20',
      defDeliveryDate: '2026-04-15', videocall: false,
      memo: '할인/초동 반영100%/무특전/전광판 광고/7만 무배',
    },
    {
      id: 'cs1774545824537', categoryId: catId,
      name: '[음총] 버프즈', distId: 'dcs1774619302089', country: 'KR',
      round: null, isMusicStreamTeam: true,
      unpoAlbumKey: '',
      priceMode: 'custom',
      customPrices: { PHOTOBOOK: 19000, POCAALBUM: 7790, ID_PASS: 14155, INVENTORY: 16245 },
      purchaseStart: '2026-03-24T02:23', purchaseEnd: '2026-04-03T23:59',
      offlineStart: '', offlineEnd: '', offlineHours: '', offlineAddress: '', offlineNote: '',
      offlineLuckyDraw: false, defDomShip: 0, defOvsShip: 0,
      url: 'https://x.com/Plave_Album/status/2036291046146265331?s=20',
      defDeliveryDate: '2026-04-14', videocall: false,
      memo: '할인/초동 반영100%/무특전/무료배송\n앨범 발매 당일 발송 보장',
    },
    {
      id: 'cs1774545708995', categoryId: catId,
      name: '[음총] 비트로드', distId: 'dcs1774619310313', country: 'KR',
      round: null, isMusicStreamTeam: true,
      unpoAlbumKey: '',
      priceMode: 'custom',
      customPrices: { PHOTOBOOK: 16500, POCAALBUM: 6900, ID_PASS: 12400, INVENTORY: 14200 },
      purchaseStart: '2026-03-24T02:21', purchaseEnd: '2026-04-12T23:59',
      offlineStart: '', offlineEnd: '', offlineHours: '', offlineAddress: '', offlineNote: '',
      offlineLuckyDraw: false, defDomShip: 0, defOvsShip: 0,
      url: 'https://x.com/Plave_Album/status/2036292541986001367?s=20',
      defDeliveryDate: '2026-04-14', videocall: false,
      memo: '앨범 발매 당일부터 순차 발송 / 3만원 이상 무료 배송',
    },
    {
      id: 'cs1774545544751', categoryId: catId,
      name: '[음총] 케타포', distId: 'dcs1774619329527', country: 'KR',
      round: null, isMusicStreamTeam: true,
      unpoAlbumKey: '',
      priceMode: 'custom',
      customPrices: { PHOTOBOOK: 16700, POCAALBUM: 7000, ID_PASS: 12500, INVENTORY: 14300 },
      purchaseStart: '2026-03-24T02:18', purchaseEnd: '2026-04-14T17:00',
      offlineStart: '', offlineEnd: '', offlineHours: '', offlineAddress: '', offlineNote: '',
      offlineLuckyDraw: false, defDomShip: 0, defOvsShip: 0,
      url: 'https://kr.ktown4u.com/eventinfo?eve_no=44113596&biz_no=967',
      defDeliveryDate: '2026-04-15', videocall: false,
      memo: '3만원 이상 구매 시 무료배송',
    },
    {
      id: 'cs1775249000001', categoryId: catId,
      name: '사운드웨이브', distId: 'dcs1775249000000', country: 'KR',
      round: null, isMusicStreamTeam: false,
      unpoAlbumKey: 'INVENTORY',
      priceMode: 'custom',
      customPrices: { PHOTOBOOK: null, POCAALBUM: null, ID_PASS: null, INVENTORY: 17100 },
      purchaseStart: '2026-04-05T11:00', purchaseEnd: '2026-04-07T23:59',
      purchaseEndTxt: '특전 소진시까지',
      offlineStart: '', offlineEnd: '', offlineHours: '', offlineAddress: '', offlineNote: '',
      offlineLuckyDraw: false, defDomShip: 0, defOvsShip: 0,
      url: 'https://www.soundwavemusic.co.kr',
      defDeliveryDate: '', videocall: true,
      memo: 'Inventory 구매 시 미공포 5종 중 랜덤 1종 증정\n영상통화 이벤트 진행',
    },
    {
      id: 'cs1774664589091', categoryId: catId,
      name: '뮤직플랜트 (영통)', distId: 'dcs1774663794920', country: 'KR',
      round: null, isMusicStreamTeam: false,
      unpoAlbumKey: 'INVENTORY',
      priceMode: 'country', customPrices: {},
      purchaseStart: '2026-03-28T11:00', purchaseEnd: '2026-03-31T23:59',
      offlineStart: '', offlineEnd: '', offlineHours: '', offlineAddress: '', offlineNote: '',
      offlineLuckyDraw: false, defDomShip: 0, defOvsShip: 0,
      url: 'https://www.musicplant.co.kr/board/?db=gallery_1&no=1320',
      defDeliveryDate: '', videocall: true,
      memo: '응모 기간 내 Inventory 구매고객 중 50명 추첨 사인포카 증정\n영통: 2026년 4월 26일',
    },
    {
      id: 'cs1774700960047', categoryId: catId,
      name: '뮤직플랜트', distId: 'dcs1774663794920', country: 'KR',
      round: null, isMusicStreamTeam: false,
      unpoAlbumKey: '',
      priceMode: 'country', customPrices: {},
      purchaseStart: '2026-03-28T11:00', purchaseEnd: '2026-04-14T23:59',
      offlineStart: '', offlineEnd: '', offlineHours: '', offlineAddress: '', offlineNote: '',
      offlineLuckyDraw: false, defDomShip: 0, defOvsShip: 0,
      url: 'https://www.musicplant.co.kr/shop/search_result.php?search_str=caligo',
      defDeliveryDate: '', videocall: false, memo: '',
    },
    {
      id: 'cs1774874734719', categoryId: catId,
      name: '[음총] 타워레코드 (2차)', distId: 'dcs1774546040116', country: 'KR',
      round: 2, isMusicStreamTeam: true,
      unpoAlbumKey: 'ID_PASS',
      priceMode: 'custom',
      customPrices: { PHOTOBOOK: null, POCAALBUM: null, ID_PASS: 24410, INVENTORY: null },
      purchaseStart: '2026-03-30T11:00', purchaseEnd: '2026-04-07T18:00',
      offlineStart: '', offlineEnd: '', offlineHours: '', offlineAddress: '', offlineNote: '',
      offlineLuckyDraw: false, defDomShip: 0, defOvsShip: 0,
      url: 'https://09platform.com/surl/P/1312',
      defDeliveryDate: '2026-05-15', videocall: false,
      memo: '★ 1차 공동구매와 묶음 배송 불가능합니다 ★\n출고 일정 : 05월 중 ~ 05월 말 예상',
    },
    {
      id: 'cs1774874856715', categoryId: catId,
      name: '[음총] HMV (2차)', distId: 'dcs1774546040116', country: 'KR',
      round: 2, isMusicStreamTeam: true,
      unpoAlbumKey: 'ID_PASS',
      priceMode: 'custom',
      customPrices: { PHOTOBOOK: null, POCAALBUM: null, ID_PASS: 24410, INVENTORY: null },
      purchaseStart: '2026-03-30T11:00', purchaseEnd: '2026-04-07T18:00',
      offlineStart: '', offlineEnd: '', offlineHours: '', offlineAddress: '', offlineNote: '',
      offlineLuckyDraw: false, defDomShip: 0, defOvsShip: 0,
      url: 'https://09platform.com/surl/P/1312',
      defDeliveryDate: '2026-05-15', videocall: false,
      memo: '★ 1차 공동구매와 묶음 배송 불가능합니다 ★\n출고 일정 : 05월 중 ~ 05월 말 예상',
    },
    {
      id: 'cs1775049657392', categoryId: catId,
      name: '이즈위', distId: 'dcs1775049442175', country: 'CN',
      round: null, isMusicStreamTeam: false,
      unpoAlbumKey: 'PHOTOBOOK',
      priceMode: 'custom',
      customPrices: { PHOTOBOOK: 156, POCAALBUM: 46, ID_PASS: 78, INVENTORY: 88 },
      purchaseStart: '2026-04-01T11:00', purchaseEnd: '2026-04-04T22:59',
      offlineStart: '', offlineEnd: '', offlineHours: '', offlineAddress: '', offlineNote: '',
      offlineLuckyDraw: false, defDomShip: 0, defOvsShip: 0,
      url: 'https://www.withfans.com/#/idolDetail?idol_id=6869',
      defDeliveryDate: '', videocall: true,
      memo: '영통 당첨자 발표: 4월 7일 18:00\n영통일정: 2026년 5월 9일',
    },
    {
      id: 'cs1775565948835', categoryId: catId,
      name: '[음총] WEVERSE JP', distId: 'dcs1774546040116', country: 'KR',
      round: null, isMusicStreamTeam: true,
      unpoAlbumKey: 'POCAALBUM',
      priceMode: 'custom',
      customPrices: { PHOTOBOOK: null, POCAALBUM: 13720, ID_PASS: null, INVENTORY: null },
      purchaseStart: '2026-04-07T11:00', purchaseEnd: '2026-04-30T18:00',
      purchaseEndTxt: '조기소진 시 마감',
      offlineStart: '', offlineEnd: '', offlineHours: '', offlineAddress: '', offlineNote: '',
      offlineLuckyDraw: false, defDomShip: 0, defOvsShip: 0,
      url: 'https://09platform.com/surl/P/1314',
      defDeliveryDate: '2026-06-09', videocall: false,
      memo: '초동반영불가\n출고일정: 6월 말 - 7월 초',
    },
    {
      id: 'cs1775566240225', categoryId: catId,
      name: 'WEVERSE JP', distId: 'dcs1774619738077', country: 'JP',
      round: null, isMusicStreamTeam: false,
      unpoAlbumKey: 'POCAALBUM',
      priceMode: 'custom',
      customPrices: { PHOTOBOOK: 3245, POCAALBUM: 1320, ID_PASS: 2420, INVENTORY: 2750 },
      purchaseStart: '2026-04-07T11:00', purchaseEnd: '',
      purchaseEndTxt: '특전 소진시까지',
      offlineStart: '', offlineEnd: '', offlineHours: '', offlineAddress: '', offlineNote: '',
      offlineLuckyDraw: false, defDomShip: 0, defOvsShip: 0,
      url: 'https://shop.weverse.io/ko/shop/JPY/artists/167/categories/3719',
      defDeliveryDate: '2026-06-09', videocall: false,
      memo: '포토북, ID Pass: 특전 없음 / 포카앨범: 미공포 5장\n인벤토리: 엽서 1매',
    },
    {
      id: 'cs1775566533743', categoryId: catId,
      name: 'Universal JP', distId: 'dcs1775566277516', country: 'JP',
      round: null, isMusicStreamTeam: false,
      unpoAlbumKey: 'PHOTOBOOK',
      priceMode: 'custom',
      customPrices: { PHOTOBOOK: 3245, POCAALBUM: 1320, ID_PASS: null, INVENTORY: 2750 },
      purchaseStart: '2026-04-07T11:00', purchaseEnd: '',
      purchaseEndTxt: '특전 소진시까지',
      offlineStart: '', offlineEnd: '', offlineHours: '', offlineAddress: '', offlineNote: '',
      offlineLuckyDraw: false, defDomShip: 0, defOvsShip: 0,
      url: 'https://store-annex.universal-music.co.jp/product/dsku15815/',
      defDeliveryDate: '2026-06-09', videocall: false,
      memo: '인벤토리/포카버전 구매 시 엽서 1매 / 포토북 구매시 미공포 증정',
    },
    {
      id: 'cs1775737339629', categoryId: catId,
      name: '[음총] Universal JP', distId: 'dcs1774546040116', country: 'KR',
      round: null, isMusicStreamTeam: true,
      unpoAlbumKey: 'PHOTOBOOK',
      priceMode: 'custom',
      customPrices: { PHOTOBOOK: 32740, POCAALBUM: null, ID_PASS: null, INVENTORY: null },
      purchaseStart: '2026-04-07T11:00', purchaseEnd: '2026-04-11T23:59',
      offlineStart: '', offlineEnd: '', offlineHours: '', offlineAddress: '', offlineNote: '',
      offlineLuckyDraw: false, defDomShip: 0, defOvsShip: 0,
      url: 'https://09platform.com/product/',
      defDeliveryDate: '2026-06-15', videocall: false, memo: '',
    },
    {
      id: 'cs1775737775955', categoryId: catId,
      name: '케타포', distId: 'dcs1774619329527', country: 'KR',
      round: null, isMusicStreamTeam: false,
      unpoAlbumKey: 'POCAALBUM',
      priceMode: 'custom',
      customPrices: { PHOTOBOOK: null, POCAALBUM: 8200, ID_PASS: null, INVENTORY: null },
      purchaseStart: '2026-04-14T11:00', purchaseEnd: '2026-04-20T20:00',
      offlineStart: '2026-04-14', offlineEnd: '2026-04-20',
      offlineHours: '11:00 - 20:00 (15-16시 브레이크)',
      offlineAddress: '케타포 인사 / 케타포 코엑스',
      offlineNote: '포카앨범 구매 시 미공포\n스페셜메뉴 구매 시 컨셉포토카드',
      offlineLuckyDraw: false, defDomShip: 0, defOvsShip: 0,
      url: 'https://kr.ktown4u.com/iteminfo?goods_no=159360',
      defDeliveryDate: '', videocall: false, memo: '',
    },
    {
      id: 'cs1776085066455', categoryId: catId,
      name: '위드뮤', distId: 'dcs1776084976682', country: 'KR',
      round: null, isMusicStreamTeam: false,
      unpoAlbumKey: 'INVENTORY',
      priceMode: 'custom',
      customPrices: { PHOTOBOOK: null, POCAALBUM: null, ID_PASS: null, INVENTORY: 17100 },
      purchaseStart: '2026-04-13T11:00', purchaseEnd: '2026-04-16T23:59',
      offlineStart: '', offlineEnd: '', offlineHours: '', offlineAddress: '', offlineNote: '',
      offlineLuckyDraw: false, defDomShip: 0, defOvsShip: 0,
      url: 'https://withmuu.com/goods/event_sale.php?sno=1333',
      defDeliveryDate: '', videocall: true,
      memo: '영통응모 발표 4/17 2시',
    },
    {
      id: 'cs1776085185495', categoryId: catId,
      name: 'Youtube', distId: 'dcs1776085087300', country: 'KR',
      round: null, isMusicStreamTeam: false,
      unpoAlbumKey: 'POCAALBUM',
      priceMode: 'custom',
      customPrices: { PHOTOBOOK: 20000, POCAALBUM: 8200, ID_PASS: 14900, INVENTORY: 17100 },
      purchaseStart: '2026-04-13T18:00', purchaseEnd: '2026-04-20T23:00',
      offlineStart: '', offlineEnd: '', offlineHours: '', offlineAddress: '', offlineNote: '',
      offlineLuckyDraw: false, defDomShip: 0, defOvsShip: 0,
      url: 'https://www.youtube.com/@plave_official/store',
      defDeliveryDate: '', videocall: true, memo: '',
    },
    {
      id: 'cs1776171151326', categoryId: catId,
      name: 'VLASTSHOP', distId: 'dcs1774543391747', country: 'KR',
      round: null, isMusicStreamTeam: false,
      unpoAlbumKey: 'POCAALBUM',
      priceMode: 'custom',
      customPrices: { PHOTOBOOK: null, POCAALBUM: 8200, ID_PASS: null, INVENTORY: null },
      purchaseStart: '2026-04-14T11:00', purchaseEnd: '2026-04-20T23:00',
      offlineStart: '', offlineEnd: '', offlineHours: '', offlineAddress: '', offlineNote: '',
      offlineLuckyDraw: false, defDomShip: 0, defOvsShip: 0,
      url: 'https://vlastshop.com/product/',
      defDeliveryDate: '', videocall: true,
      memo: '영통발표: 4/21 ; 드라이빙토크회: 5/31',
    },
    {
      id: 'cs1776402107838', categoryId: catId,
      name: '버프즈', distId: 'dcs1774619302089', country: 'KR',
      round: null, isMusicStreamTeam: false,
      unpoAlbumKey: 'INVENTORY',
      priceMode: 'country', customPrices: {},
      purchaseStart: '2026-04-17T11:00', purchaseEnd: '2026-04-19T23:59',
      offlineStart: '', offlineEnd: '', offlineHours: '', offlineAddress: '', offlineNote: '',
      offlineLuckyDraw: false, defDomShip: 0, defOvsShip: 0,
      url: 'https://buffz.co.kr/article/event/8/168196/',
      defDeliveryDate: '', videocall: true, memo: '',
    },
  ];

  state.purchases = [];
  state.unpoCards = [];

  return state;
}
